AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 bucket with CloudFront distribution and IAM user for CapitecMyCiti assets

Parameters:
  BucketName:
    Type: String
    Default: capitec-myciti-assets
    Description: Name of the S3 bucket

Resources:
  # S3 Bucket - private, only accessible via CloudFront
  AssetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, PUT, POST]
            AllowedOrigins: ['*']
            MaxAge: 3600

  # Origin Access Control for CloudFront -> S3
  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${BucketName}-oac"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub "CDN for ${BucketName}"
        DefaultRootObject: index.html
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt AssetsBucket.RegionalDomainName
            OriginAccessControlId: !GetAtt CloudFrontOAC.Id
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD]
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          Compress: true
        PriceClass: PriceClass_200

  # Bucket policy allowing CloudFront to read objects
  AssetsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AssetsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${BucketName}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

  # IAM User with write access to the bucket
  AssetUploadUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "${BucketName}-uploader"
      Policies:
        - PolicyName: !Sub "${BucketName}-write-policy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:GetObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:aws:s3:::${BucketName}"
                  - !Sub "arn:aws:s3:::${BucketName}/*"

  # Access key for the IAM user
  AssetUploadUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref AssetUploadUser

Outputs:
  BucketName:
    Description: S3 Bucket Name
    Value: !Ref AssetsBucket

  BucketArn:
    Description: S3 Bucket ARN
    Value: !GetAtt AssetsBucket.Arn

  CloudFrontDomain:
    Description: CloudFront Distribution Domain (use this URL to display images)
    Value: !GetAtt CloudFrontDistribution.DomainName

  CloudFrontDistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref CloudFrontDistribution

  UploaderUserName:
    Description: IAM User for uploading assets
    Value: !Ref AssetUploadUser

  AccessKeyId:
    Description: Access Key ID for the uploader user
    Value: !Ref AssetUploadUserAccessKey

  SecretAccessKey:
    Description: Secret Access Key for the uploader user
    Value: !GetAtt AssetUploadUserAccessKey.SecretAccessKey
